"use client";

import { useEffect, useState, useRef } from "react";
import { useParams } from "next/navigation";
import { Star, Github, MapPin, ArrowUpRight, ExternalLink } from "lucide-react";
import { buildApiUrl } from "@/lib/config";

const API = buildApiUrl("");

interface Project {
  name: string;
  description: string;
  url: string;
  stars: number;
  language: string | null;
}

interface PortfolioData {
  name: string;
  bio: string;
  tagline?: string;
  highlights?: string[];
  github_url: string;
  avatar_url?: string;
  username?: string;
  location?: string;
  company?: string;
  theme: string;
  accent_hue?: number;
  projects: Project[];
  skills: string[];
  design_emoji?: string;
  interactive_bg?: boolean;
  cta_text?: string;
  html?: string;  // Custom HTML generated by Gemini
  design_config?: {
    color_mood: string;
    layout: string;
    background: string;
    animation_level: string;
    typography: string;
    spacing: string;
    avatar_motion: string;
    project_style: string;
    sections: string[];
  };
}

// Cursor-following emoji component with head tilt
function CursorEmoji({ emoji, size = "2rem" }: { emoji: string; size?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const pos = useRef({ x: -200, y: -200 });
  const centerRef = useRef({ x: 0, y: 0 });

  useEffect(() => {
    centerRef.current = { x: window.innerWidth / 2, y: window.innerHeight / 2 };
    const move = (e: MouseEvent) => {
      pos.current = { x: e.clientX, y: e.clientY };
      // Calculate head tilt angle toward cursor
      if (ref.current) {
        const dx = e.clientX - centerRef.current.x;
        const dy = e.clientY - centerRef.current.y;
        const angle = Math.atan2(dy, dx) * (180 / Math.PI);
        ref.current.style.transform = `translate(${e.clientX - 40}px, ${e.clientY - 40}px) rotate(${angle * 0.3}deg)`;
      }
    };
    window.addEventListener("mousemove", move);
    return () => { window.removeEventListener("mousemove", move); };
  }, []);

  return (
    <div ref={ref} className="fixed top-0 left-0 z-50 pointer-events-none select-none"
      style={{ fontSize: size, transition: "transform 0.1s ease-out", willChange: "transform" }}>
      {emoji}
    </div>
  );
}

// Interactive animated background with gradient support
function InteractiveBg({ hue, gradient }: { hue: number; gradient?: { from: string; to: string } }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const mouse = useRef({ x: 0, y: 0 });

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d")!;
    let w = canvas.width = window.innerWidth;
    let h = canvas.height = window.innerHeight;
    const onResize = () => { w = canvas.width = window.innerWidth; h = canvas.height = window.innerHeight; };
    window.addEventListener("resize", onResize);
    window.addEventListener("mousemove", (e) => { mouse.current = { x: e.clientX, y: e.clientY }; });

    // Floating dots
    const dots = Array.from({ length: 55 }, () => ({
      x: Math.random() * window.innerWidth,
      y: Math.random() * window.innerHeight,
      r: Math.random() * 2.5 + 1,
      vx: (Math.random() - 0.5) * 0.4,
      vy: (Math.random() - 0.5) * 0.4,
      opacity: Math.random() * 0.4 + 0.1,
    }));

    let frame = 0;
    const draw = () => {
      // Draw gradient background if specified
      if (gradient) {
        const g = ctx.createLinearGradient(0, 0, w, h);
        g.addColorStop(0, gradient.from);
        g.addColorStop(1, gradient.to);
        ctx.fillStyle = g;
        ctx.fillRect(0, 0, w, h);
      } else {
        ctx.clearRect(0, 0, w, h);
      }

      // Mouse glow
      const glowGrad = ctx.createRadialGradient(mouse.current.x, mouse.current.y, 0, mouse.current.x, mouse.current.y, 280);
      glowGrad.addColorStop(0, `hsla(${hue},80%,65%,0.12)`);
      glowGrad.addColorStop(1, `hsla(${hue},80%,65%,0)`);
      ctx.fillStyle = glowGrad;
      ctx.fillRect(0, 0, w, h);

      dots.forEach(d => {
        d.x += d.vx; d.y += d.vy;
        if (d.x < 0 || d.x > w) d.vx *= -1;
        if (d.y < 0 || d.y > h) d.vy *= -1;
        dots.forEach(d2 => {
          const dx = d.x - d2.x, dy = d.y - d2.y;
          const dist = Math.sqrt(dx*dx + dy*dy);
          if (dist < 110) {
            ctx.beginPath();
            ctx.moveTo(d.x, d.y);
            ctx.lineTo(d2.x, d2.y);
            ctx.strokeStyle = `hsla(${hue},60%,70%,${0.12 * (1 - dist/110)})`;
            ctx.lineWidth = 0.8;
            ctx.stroke();
          }
        });
        ctx.beginPath();
        ctx.arc(d.x, d.y, d.r, 0, Math.PI * 2);
        ctx.fillStyle = `hsla(${hue},70%,70%,${d.opacity})`;
        ctx.fill();
      });
      frame = requestAnimationFrame(draw);
    };
    draw();
    return () => { cancelAnimationFrame(frame); window.removeEventListener("resize", onResize); };
  }, [hue, gradient]);

  return <canvas ref={canvasRef} className="fixed inset-0 pointer-events-none z-0" />;
}

interface Portfolio {
  id: string;
  slug: string;
  theme: string;
  last_built_at: string | null;
  portfolio_data: PortfolioData;
}

const LANG_COLORS: Record<string, string> = {
  TypeScript: "#3178c6", JavaScript: "#f7df1e", Python: "#3572A5",
  Rust: "#dea584", Go: "#00ADD8", Java: "#b07219",
  "C++": "#f34b7d", C: "#555555", Ruby: "#701516",
  Swift: "#fa7343", Kotlin: "#A97BFF", Dart: "#00B4AB",
};

export default function PortfolioPage() {
  const params = useParams();
  const username = params.username as string;
  const [portfolio, setPortfolio] = useState<Portfolio | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    if (!username) return;
    fetch(`${API}/api/portfolio/public/${username}`)
      .then((res) => { if (res.status === 404) { setNotFound(true); return null; } return res.json(); })
      .then((data) => { if (data) setPortfolio(data); })
      .catch(() => setNotFound(true))
      .finally(() => setLoading(false));
  }, [username]);

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-10 h-10 border-2 border-violet-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-gray-500 text-sm">Loading portfolio…</p>
        </div>
      </div>
    );
  }

  if (notFound || !portfolio) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center text-center px-4">
        <div>
          <p className="text-7xl mb-6">🔍</p>
          <h1 className="text-3xl font-bold text-white mb-3">Portfolio not found</h1>
          <p className="text-gray-500">@{username} hasn't built their portfolio yet.</p>
        </div>
      </div>
    );
  }

  const data = portfolio.portfolio_data;
  const config = data.design_config;
  const hue = data.accent_hue ?? 210;
  // If Gemini generated custom HTML, render that instead of the preset themes.
  if (data.html) {
    return <CustomHTMLPortfolio html={data.html} />;
  }

  // Use dynamic renderer if design_config exists, otherwise fallback to theme
  if (config && config.color_mood === "vibrant") {
    return <CreativeTheme portfolio={portfolio} data={data} />;
  }

  const theme = portfolio.theme || "minimal";
  return (
    <>
      {data.design_emoji && <CursorEmoji emoji={data.design_emoji} size={config && config.color_mood === "vibrant" ? "8rem" : "2rem"} />}
      {data.interactive_bg && <InteractiveBg hue={hue} />}
      {theme === "dark" && <DarkTheme portfolio={portfolio} data={data} />}
      {theme === "creative" && <CreativeTheme portfolio={portfolio} data={data} />}
      {theme === "minimal" && <MinimalTheme portfolio={portfolio} data={data} />}
    </>
  );
}

function CustomHTMLPortfolio({ html }: { html: string }) {
  return (
    <iframe
      className="w-full h-screen border-none"
      title="Custom Portfolio"
      srcDoc={html}
      sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox"
    />
  );
}
function MinimalTheme({ portfolio, data }: { portfolio: Portfolio; data: PortfolioData }) {
  const hue = data.accent_hue ?? 210;
  const accent = `hsl(${hue},65%,52%)`;
  const accentSoft = `hsl(${hue},65%,97%)`;
  return (
    <div className="min-h-screen bg-[#fafafa]" style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>
      {/* Top gradient bar */}
      <div className="h-[3px]" style={{ background: `linear-gradient(90deg, ${accent} 0%, hsl(${hue+50},65%,62%) 100%)` }} />

      {/* Nav */}
      <nav className="bg-white/80 backdrop-blur-sm border-b border-gray-100/80 sticky top-0 z-10">
        <div className="max-w-[720px] mx-auto px-6 h-14 flex items-center justify-between">
          <span className="font-semibold text-gray-900" style={{ letterSpacing: "-0.01em" }}>{data.name?.split(" ")[0]}</span>
          <div className="flex items-center gap-6">
            <a href="#work" className="text-sm text-gray-500 hover:text-gray-900 transition-colors">Work</a>
            <a href="#skills" className="text-sm text-gray-500 hover:text-gray-900 transition-colors">Skills</a>
            <a href={data.github_url} target="_blank" rel="noopener noreferrer"
              className="flex items-center gap-1.5 text-sm font-medium px-4 py-1.5 rounded-full border border-gray-200 text-gray-700 hover:border-gray-400 transition-all">
              <Github size={13} /> GitHub
            </a>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <div className="max-w-[720px] mx-auto px-6 pt-20 pb-16">
        <div className="flex items-start gap-7">
          {data.avatar_url && (
            <img src={data.avatar_url} alt=""
              className="w-[72px] h-[72px] rounded-2xl flex-shrink-0 ring-1 ring-black/5 shadow-sm" />
          )}
          <div className="flex-1">
            <div className="flex items-center gap-3 mb-3">
              <h1 className="text-[2.2rem] font-bold text-gray-950 tracking-tight leading-none">{data.name}</h1>
              {data.location && (
                <span className="flex items-center gap-1 text-xs text-gray-400 mt-1">
                  <MapPin size={11} />{data.location}
                </span>
              )}
            </div>
            <p className="text-[1.05rem] text-gray-500 leading-[1.7] max-w-[520px] mb-6">{data.bio}</p>
            <a href={data.github_url} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm font-medium px-5 py-2.5 rounded-lg text-white shadow-sm transition-all hover:opacity-90"
              style={{ background: accent }}>
              <Github size={14} /> @{portfolio.slug}
            </a>
          </div>
        </div>
      </div>

      {/* Divider */}
      <div className="max-w-[720px] mx-auto px-6"><div className="border-t border-gray-100" /></div>

      {/* Skills */}
      {data.skills && data.skills.length > 0 && (
        <div id="skills" className="max-w-[720px] mx-auto px-6 py-12">
          <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-gray-400 mb-5">Tech Stack</p>
          <div className="flex flex-wrap gap-2">
            {data.skills.map((s, i) => (
              <span key={i} className="flex items-center gap-2 text-sm font-medium px-3.5 py-1.5 rounded-full bg-white border border-gray-200 text-gray-700 shadow-sm">
                <span className="w-2 h-2 rounded-full" style={{ background: LANG_COLORS[s] || accent }} />
                {s}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Work */}
      <div id="work" className="max-w-[720px] mx-auto px-6 pb-24">
        <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-gray-400 mb-5">Selected Work</p>
        <div className="space-y-3">
          {data.projects?.map((p, i) => (
            <a key={i} href={p.url} target="_blank" rel="noopener noreferrer"
              className="group flex items-start gap-5 p-5 bg-white rounded-2xl border border-gray-100 hover:border-gray-300 hover:shadow-md transition-all">
              <div className="w-10 h-10 rounded-xl flex-shrink-0 flex items-center justify-center text-sm font-black text-white shadow-sm" style={{ background: `hsl(${(hue + i * 30) % 360},65%,58%)` }}>
                {p.name[0].toUpperCase()}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-3 mb-1">
                  <span className="font-semibold text-gray-900">{p.name}</span>
                  {p.language && <span className="text-xs text-gray-400 font-mono">{p.language}</span>}
                  {p.stars > 0 && <span className="flex items-center gap-0.5 text-xs text-amber-500"><Star size={10} fill="currentColor" />{p.stars}</span>}
                </div>
                {p.description && <p className="text-sm text-gray-500 leading-relaxed">{p.description}</p>}
              </div>
              <ArrowUpRight size={16} className="text-gray-300 group-hover:text-gray-600 flex-shrink-0 mt-1 transition-colors" />
            </a>
          ))}
        </div>
      </div>

      <footer className="border-t border-gray-100 py-8 bg-white">
        <div className="max-w-[720px] mx-auto px-6 flex items-center justify-between">
          <span className="text-sm text-gray-400">@{portfolio.slug}</span>
          <span className="text-xs text-gray-300">Built with PortfolioAI</span>
        </div>
      </footer>
    </div>
  );
}

function DarkTheme({ portfolio, data }: { portfolio: Portfolio; data: PortfolioData }) {
  const hue = data.accent_hue ?? 260;
  const glow = `hsl(${hue},75%,62%)`;
  const glowDim = `hsl(${hue},75%,62%,0.12)`;
  return (
    <div className="min-h-screen bg-[#080808] text-white overflow-x-hidden" style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>
      {/* Background orbs */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-[700px] h-[500px] rounded-full blur-[120px] opacity-[0.07]" style={{ background: glow }} />
        <div className="absolute top-1/2 -right-40 w-[400px] h-[400px] rounded-full blur-[100px] opacity-[0.05]" style={{ background: `hsl(${hue+50},75%,62%)` }} />
      </div>

      {/* Navbar */}
      <nav className="relative border-b border-white/[0.06] backdrop-blur-md">
        <div className="max-w-5xl mx-auto px-8 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
            <span className="text-sm font-mono text-gray-400">@{portfolio.slug}</span>
          </div>
          <a href={data.github_url} target="_blank" rel="noopener noreferrer"
            className="flex items-center gap-2 text-sm border rounded-lg px-4 py-1.5 transition-all"
            style={{ borderColor: `${glow}30`, color: glow, background: `${glow}08` }}>
            <Github size={14} /> GitHub
          </a>
        </div>
      </nav>

      <div className="relative max-w-5xl mx-auto px-8">
        {/* Hero */}
        <div className="pt-28 pb-24">
          <div className="flex flex-col md:flex-row items-start gap-10">
            {data.avatar_url && (
              <div className="relative flex-shrink-0">
                <div className="absolute inset-0 rounded-3xl blur-xl opacity-30" style={{ background: glow }} />
                <img src={data.avatar_url} alt="" className="relative w-28 h-28 rounded-3xl ring-1 ring-white/10" />
              </div>
            )}
            <div>
              <p className="text-xs font-mono mb-3" style={{ color: glow }}>Software Engineer</p>
              <h1 className="text-5xl md:text-6xl font-black leading-none tracking-tight mb-5" style={{ letterSpacing: "-0.03em" }}>
                <span className="bg-gradient-to-br from-white to-gray-400 bg-clip-text text-transparent">{data.name}</span>
              </h1>
              <p className="text-gray-400 text-lg max-w-xl leading-relaxed mb-6">{data.bio}</p>
              {(data.location || data.company) && (
                <p className="flex items-center gap-4 text-sm text-gray-600 mb-6">
                  {data.location && <span className="flex items-center gap-1.5"><MapPin size={12} className="text-gray-500" />{data.location}</span>}
                  {data.company && <span>{data.company}</span>}
                </p>
              )}
              <a href={data.github_url} target="_blank" rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-sm font-semibold px-5 py-2.5 rounded-xl text-white transition-all hover:opacity-80"
                style={{ background: `linear-gradient(135deg, ${glow}, hsl(${hue+40},75%,62%))` }}>
                <Github size={14} /> View Profile
              </a>
            </div>
          </div>
        </div>

        {/* Tech stack */}
        {data.skills && data.skills.length > 0 && (
          <div className="py-10 border-t border-white/[0.05]">
            <p className="text-[11px] font-semibold uppercase tracking-[0.15em] text-gray-600 mb-6">Technologies</p>
            <div className="flex flex-wrap gap-3">
              {data.skills.map((s, i) => (
                <div key={i} className="flex items-center gap-2 px-4 py-2 rounded-xl border border-white/[0.08] bg-white/[0.03] text-sm text-gray-300">
                  <span className="w-2.5 h-2.5 rounded-full" style={{ background: LANG_COLORS[s] || glow }} />
                  {s}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Projects */}
        <div className="py-10 border-t border-white/[0.05] pb-24">
          <p className="text-[11px] font-semibold uppercase tracking-[0.15em] text-gray-600 mb-8">Selected Projects</p>
          <div className="grid md:grid-cols-2 gap-4">
            {data.projects?.map((p, i) => (
              <a key={i} href={p.url} target="_blank" rel="noopener noreferrer"
                className="group relative rounded-2xl p-6 border transition-all overflow-hidden"
                style={{ borderColor: 'rgba(255,255,255,0.06)', background: 'rgba(255,255,255,0.02)' }}
                onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = `${glow}40`; (e.currentTarget as HTMLElement).style.background = `rgba(255,255,255,0.04)`; }}
                onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = 'rgba(255,255,255,0.06)'; (e.currentTarget as HTMLElement).style.background = 'rgba(255,255,255,0.02)'; }}>
                <div className="absolute top-0 left-0 w-full h-[2px] opacity-0 group-hover:opacity-100 transition-opacity" style={{ background: `linear-gradient(90deg, ${glow}, transparent)` }} />
                <div className="flex items-start justify-between mb-4">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center text-xs font-bold" style={{ background: `${glow}18`, color: glow }}>
                    {p.name[0]?.toUpperCase()}
                  </div>
                  <ExternalLink size={14} className="text-gray-700 group-hover:text-gray-400 transition-colors" />
                </div>
                <h3 className="font-bold text-white mb-2">{p.name}</h3>
                {p.description && <p className="text-sm text-gray-500 leading-relaxed mb-4 line-clamp-2">{p.description}</p>}
                <div className="flex items-center gap-3">
                  {p.language && (
                    <span className="flex items-center gap-1.5 text-xs text-gray-600">
                      <span className="w-2 h-2 rounded-full" style={{ background: LANG_COLORS[p.language] || '#888' }} />{p.language}
                    </span>
                  )}
                  {p.stars > 0 && <span className="text-xs text-amber-500/70 flex items-center gap-1"><Star size={10} fill="currentColor" />{p.stars}</span>}
                </div>
              </a>
            ))}
          </div>
        </div>
      </div>

      <footer className="border-t border-white/[0.05] py-8">
        <div className="max-w-5xl mx-auto px-8 flex items-center justify-between">
          <span className="text-xs font-mono text-gray-700">@{portfolio.slug}</span>
          <span className="text-xs text-gray-800">PortfolioAI</span>
        </div>
      </footer>
    </div>
  );
}

function CreativeTheme({ portfolio, data }: { portfolio: Portfolio; data: PortfolioData }) {
  const hue = data.accent_hue ?? 45;
  const accent = `hsl(${hue},90%,58%)`;
  const accentDark = `hsl(${hue},80%,45%)`;
  return (
    <div className="min-h-screen bg-white" style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>
      {/* Full-screen hero */}
      <div className="min-h-screen grid grid-cols-1 md:grid-cols-[1fr_420px] relative">
        {/* Left panel */}
        <div className="bg-[#0a0a0a] flex flex-col justify-between p-10 md:p-16 min-h-[60vh] md:min-h-screen">
          <div className="flex items-center justify-between">
            {data.avatar_url && (
              <img src={data.avatar_url} alt="" className="w-12 h-12 rounded-2xl border border-white/10" />
            )}
            <a href={data.github_url} target="_blank" rel="noopener noreferrer"
              className="flex items-center gap-2 text-xs text-gray-500 hover:text-white transition-colors border border-gray-800 rounded-full px-4 py-2">
              <Github size={13} /> GitHub
            </a>
          </div>

          <div className="mt-auto pt-16">
            <div className="text-[clamp(3.5rem,8vw,7rem)] font-black leading-[0.88] tracking-tighter text-white mb-8" style={{ wordBreak: 'break-word' }}>
              {data.name?.split(" ").map((w, i) => (
                <div key={i} style={{ color: i % 2 === 1 ? accent : 'white' }}>{w}</div>
              ))}
            </div>
            {(data.location || data.company) && (
              <p className="flex items-center gap-3 text-sm text-gray-500">
                {data.location && <span className="flex items-center gap-1.5"><MapPin size={12} />{data.location}</span>}
                {data.company && <span>· {data.company}</span>}
              </p>
            )}
          </div>
        </div>

        {/* Right panel */}
        <div className="flex flex-col justify-between p-10 md:p-12" style={{ background: accent }}>
          <div />
          <div className="mt-auto">
            <p className="text-[1.35rem] font-semibold text-black leading-snug mb-8" style={{ lineHeight: '1.5' }}>{data.bio}</p>
            {data.skills && data.skills.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-8">
                {data.skills.slice(0, 7).map((s, i) => (
                  <span key={i} className="text-xs font-bold px-3 py-1.5 rounded-full text-black" style={{ background: 'rgba(0,0,0,0.12)' }}>{s}</span>
                ))}
              </div>
            )}
            <a href={data.github_url} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm font-black uppercase tracking-wide px-6 py-3 text-white transition-all hover:opacity-80"
              style={{ background: '#0a0a0a' }}>
              View Work <ArrowUpRight size={16} />
            </a>
          </div>
        </div>
      </div>

      {/* Projects section */}
      <div className="bg-white">
        <div className="max-w-6xl mx-auto px-8 py-24">
          <div className="flex items-end justify-between mb-16">
            <h2 className="text-[clamp(2.5rem,5vw,4rem)] font-black leading-none tracking-tighter">Selected<br /><span style={{ color: accent }}>Work.</span></h2>
            <span className="text-sm text-gray-400">{data.projects?.length || 0} projects</span>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {data.projects?.map((p, i) => (
              <a key={i} href={p.url} target="_blank" rel="noopener noreferrer"
                className="group block border-2 border-gray-100 hover:border-black p-6 transition-all duration-200 rounded-2xl hover:-translate-y-1">
                <div className="flex items-start justify-between mb-6">
                  <div className="text-3xl font-black text-gray-100 group-hover:text-black transition-colors">0{i+1}</div>
                  <ArrowUpRight size={18} className="text-gray-300 group-hover:text-black transition-colors" />
                </div>
                <h3 className="text-lg font-black mb-2 tracking-tight">{p.name}</h3>
                {p.description && <p className="text-sm text-gray-500 leading-relaxed mb-5 line-clamp-2">{p.description}</p>}
                <div className="flex items-center gap-3 pt-4 border-t border-gray-100">
                  {p.language && (
                    <span className="flex items-center gap-1.5 text-xs font-semibold text-gray-500">
                      <span className="w-2 h-2 rounded-full" style={{ background: LANG_COLORS[p.language] || accentDark }} />{p.language}
                    </span>
                  )}
                  {p.stars > 0 && <span className="text-xs text-amber-500 flex items-center gap-1 font-semibold"><Star size={10} fill="currentColor" />{p.stars}</span>}
                </div>
              </a>
            ))}
          </div>
        </div>
      </div>

      <footer className="border-t-2 border-black py-8 bg-[#0a0a0a]">
        <div className="max-w-6xl mx-auto px-8 flex items-center justify-between">
          <span className="text-sm font-black text-white">@{portfolio.slug}</span>
          <span className="text-xs font-semibold" style={{ color: accent }}>PortfolioAI</span>
        </div>
      </footer>
    </div>
  );
}
